spring:
  security:
    user:
      name: sa
      password: sa

  datasource:
    url: jdbc:h2:mem:usermanagementdb
    username: sa
    password: sa

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 3000
