spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: yaksh
    password: pragra123

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080
